backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
   fields:
  - { label: "Nome", name: "title", widget: "string" }
  - { label: "Código", name: "codigo", widget: "string" }
  - { label: "Preço", name: "price", widget: "number", value_type: "float", min: 0 }
  - { label: "Categoria", name: "categoria", widget: "select", options: ["bebida", "pizza-salgada", "pizza-doce"] }
