
backend:
  name: git-gateway
  branch: principal

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "contente"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "price", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }

  - name: "textos"
    label: "Textos do Site"
    folder: "contente"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
