backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Produto", name: "title", widget: "string" }
      - { label: "Pre√ßo", name: "price", widget: "number" }
      - { label: "Imagem", name: "image", widget: "image" }