backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    files:
      - file: "content/produtos.json"
        label: "Lista de Produtos"
        name: "produtos"
        fields:
          - label: "Produtos"
            name: "produtos"
            widget: "list"
            fields:
              - { label: "Nome", name: "title", widget: "string" }
              - { label: "Código", name: "codigo", widget: "string" }
              - { label: "Preço", name: "price", widget: "number", min: 0 }
              - { 
                  label: "Categoria",
                  name: "categoria",
                  widget: "select",
                  options: ["bebida", "pizza-salgada", "pizza-doce", "combos", "bordas", "adicionais"]
                }

