backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Imagem", name: "imagem", widget: "image" }

  - name: "textos"
    label: "Textos do Site"
    folder: "content/textos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Conteúdo", name: "conteudo", widget: "text" }
