backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    files:
      - file: "content/produtos.json"
        label: "Produtos"
        name: "produtos"
        fields:
          - label: "Produtos"
            name: "produtos"
            widget: "list"
            fields:
              - { label: "Nome do Produto", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Código", name: "codigo", widget: "string" }
              - { label: "Preço", name: "price", widget: "number" }
              - { label: "Imagem", name: "image", widget: "image" }
