backend:
  name: git-gateway
  branch: main

media_folder: "imagens"
public_folder: "/imagens"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Nome do Produto", name: "title", widget: "string" }
      - { label: "Código", name: "codigo", widget: "string" }
      - { label: "Preço", name: "price", widget: "number" }
      - { label: "Imagem", name: "image", widget: "image" }
